"""empty message

Revision ID: 1844d1686059
Revises: f7846f520389
Create Date: 2024-10-31 20:10:53.996694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1844d1686059'
down_revision = 'f7846f520389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tel_contacto', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('area_lat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('area_lng', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('area_lng')
        batch_op.drop_column('area_lat')
        batch_op.drop_column('tel_contacto')

    # ### end Alembic commands ###
