"""empty message

Revision ID: bb96ea1dff59
Revises: 1844d1686059
Create Date: 2024-10-31 21:09:42.338153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb96ea1dff59'
down_revision = '1844d1686059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivos_post',
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('id_archivo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_archivo'], ['archivos.id'], ),
    sa.ForeignKeyConstraint(['id_post'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id_post', 'id_archivo')
    )
    op.create_table('mascotas_post',
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascotas.id'], ),
    sa.ForeignKeyConstraint(['id_post'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id_post', 'id_mascota')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas_post')
    op.drop_table('archivos_post')
    # ### end Alembic commands ###
