"""empty message

Revision ID: c5883e7017f3
Revises: 65f4b098c717
Create Date: 2024-09-23 21:01:37.857470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5883e7017f3'
down_revision = '65f4b098c717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascotas_usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascotas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_mascota')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creado', sa.Date(), nullable=False),
    sa.Column('fecha_modificado', sa.Date(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('mascotas_usuario')
    # ### end Alembic commands ###
