"""empty message

Revision ID: f7846f520389
Revises: 7b375d060757
Create Date: 2024-10-31 20:00:32.361305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7846f520389'
down_revision = '7b375d060757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
